development:
  adapter: postgresql
  database: picture_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: picture_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: picture_production
  pool: 5
  timeout: 5000
